project_name: git-switch

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'

brews:
  -
    tap:
      owner: alfiesal
      name: homebrew-tap

    url_template: "https://github.com/alfiesal/git-switch/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: alfiesal
      email: salomonsalfie@gmail.com

    folder: git-switch
    homepage: "https://github.com/alfiesal/git-switch"
    description: "Switch git users quickly."
    license: "MIT"


